import { createTextTemplate } from './svgTemplateFactory.js';

export const textTemplates = [
  createTextTemplate({
    key: 'dream-big',
    name: 'Dream Big',
    tags: ['motivational', 'bold'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/dream_big.svg',
    text: 'Dream Big',
    fontFamily: "'Montserrat', sans-serif",
    fontSize: 48,
    fontWeight: 700,
    fill: '#ff6b6b'
  }),
  createTextTemplate({
    key: 'stay-wild',
    name: 'Stay Wild',
    tags: ['adventure', 'script'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/stay_wild.svg',
    text: 'Stay Wild',
    fontFamily: "'Pacifico', cursive",
    fontSize: 44,
    fontWeight: 600,
    fill: '#2dd4bf'
  }),
  createTextTemplate({
    key: 'be-kind',
    name: 'Be Kind',
    tags: ['kindness', 'rounded'],
    width: 200,
    height: 110,
    previewAsset: 'assets/img/svg_text/be_kind.svg',
    text: 'Be Kind',
    fontFamily: "'Baloo 2', cursive",
    fontSize: 50,
    fontWeight: 700,
    fill: '#facc15'
  }),
  createTextTemplate({
    key: 'shine-on',
    name: 'Shine On',
    tags: ['shine', 'script'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/shine_on.svg',
    text: 'Shine On',
    fontFamily: "'Great Vibes', cursive",
    fontSize: 52,
    fontWeight: 600,
    fill: '#fbbf24'
  }),
  createTextTemplate({
    key: 'bold-moves',
    name: 'Bold Moves',
    tags: ['bold', 'stacked'],
    width: 220,
    height: 140,
    previewAsset: 'assets/img/svg_text/bold_moves.svg',
    text: 'Bold\nMoves',
    fontFamily: "'Bebas Neue', sans-serif",
    fontSize: 60,
    fontWeight: 700,
    fill: '#f97316'
  }),
  createTextTemplate({
    key: 'good-vibes',
    name: 'Good Vibes',
    tags: ['retro', 'sunset'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/good_vibes.svg',
    text: 'Good Vibes',
    fontFamily: "'Fredoka One', cursive",
    fontSize: 48,
    fontWeight: 700,
    fill: '#60a5fa'
  }),
  createTextTemplate({
    key: 'chill-mode',
    name: 'Chill Mode',
    tags: ['casual', 'script'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/chill_mode.svg',
    text: 'Chill Mode',
    fontFamily: "'Lobster', cursive",
    fontSize: 46,
    fontWeight: 600,
    fill: '#38bdf8'
  }),
  createTextTemplate({
    key: 'rise-up',
    name: 'Rise Up',
    tags: ['inspire', 'block'],
    width: 200,
    height: 120,
    previewAsset: 'assets/img/svg_text/rise_up.svg',
    text: 'Rise Up',
    fontFamily: "'Oswald', sans-serif",
    fontSize: 58,
    fontWeight: 700,
    fill: '#fb7185'
  }),
  createTextTemplate({
    key: 'sun-chaser',
    name: 'Sun Chaser',
    tags: ['sun', 'script'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/sun_chaser.svg',
    text: 'Sun Chaser',
    fontFamily: "'Sacramento', cursive",
    fontSize: 52,
    fontWeight: 600,
    fill: '#f59e0b'
  }),
  createTextTemplate({
    key: 'wander-more',
    name: 'Wander More',
    tags: ['travel', 'sans'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/wander_more.svg',
    text: 'Wander More',
    fontFamily: "'Raleway', sans-serif",
    fontSize: 42,
    fontWeight: 700,
    fill: '#22d3ee'
  }),
  createTextTemplate({
    key: 'love-wins',
    name: 'Love Wins',
    tags: ['love', 'script'],
    width: 200,
    height: 110,
    previewAsset: 'assets/img/svg_text/love_wins.svg',
    text: 'Love Wins',
    fontFamily: "'Dancing Script', cursive",
    fontSize: 48,
    fontWeight: 600,
    fill: '#fb7185'
  }),
  createTextTemplate({
    key: 'brave-soul',
    name: 'Brave Soul',
    tags: ['brave', 'block'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/brave_soul.svg',
    text: 'Brave Soul',
    fontFamily: "'Anton', sans-serif",
    fontSize: 56,
    fontWeight: 700,
    fill: '#6366f1'
  }),
  createTextTemplate({
    key: 'make-waves',
    name: 'Make Waves',
    tags: ['ocean', 'script'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/make_waves.svg',
    text: 'Make Waves',
    fontFamily: "'Satisfy', cursive",
    fontSize: 50,
    fontWeight: 600,
    fill: '#0ea5e9'
  }),
  createTextTemplate({
    key: 'keep-going',
    name: 'Keep Going',
    tags: ['motivational', 'rounded'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/keep_going.svg',
    text: 'Keep Going',
    fontFamily: "'Nunito', sans-serif",
    fontSize: 46,
    fontWeight: 800,
    fill: '#14b8a6'
  }),
  createTextTemplate({
    key: 'just-create',
    name: 'Just Create',
    tags: ['creative', 'script'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/just_create.svg',
    text: 'Just Create',
    fontFamily: "'Courgette', cursive",
    fontSize: 48,
    fontWeight: 600,
    fill: '#f472b6'
  }),
  createTextTemplate({
    key: 'think-big',
    name: 'Think Big',
    tags: ['bold', 'block'],
    width: 200,
    height: 120,
    previewAsset: 'assets/img/svg_text/think_big.svg',
    text: 'Think Big',
    fontFamily: "'Exo 2', sans-serif",
    fontSize: 54,
    fontWeight: 700,
    fill: '#f97316'
  }),
  createTextTemplate({
    key: 'stay-cozy',
    name: 'Stay Cozy',
    tags: ['comfort', 'script'],
    width: 200,
    height: 110,
    previewAsset: 'assets/img/svg_text/stay_cozy.svg',
    text: 'Stay Cozy',
    fontFamily: "'Cookie', cursive",
    fontSize: 50,
    fontWeight: 600,
    fill: '#fb923c'
  }),
  createTextTemplate({
    key: 'fresh-start',
    name: 'Fresh Start',
    tags: ['fresh', 'sans'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/fresh_start.svg',
    text: 'Fresh Start',
    fontFamily: "'Poppins', sans-serif",
    fontSize: 48,
    fontWeight: 700,
    fill: '#84cc16'
  }),
  createTextTemplate({
    key: 'wild-heart',
    name: 'Wild Heart',
    tags: ['wild', 'script'],
    width: 220,
    height: 120,
    previewAsset: 'assets/img/svg_text/wild_heart.svg',
    text: 'Wild Heart',
    fontFamily: "'Allura', cursive",
    fontSize: 54,
    fontWeight: 600,
    fill: '#f472b6'
  }),
  createTextTemplate({
    key: 'night-owl',
    name: 'Night Owl',
    tags: ['night', 'rounded'],
    width: 200,
    height: 120,
    previewAsset: 'assets/img/svg_text/night_owl.svg',
    text: 'Night Owl',
    fontFamily: "'Rubik', sans-serif",
    fontSize: 50,
    fontWeight: 700,
    fill: '#6366f1'
  })
];
