-- SQLite schema and data for product media assets
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS products (
    product_id INTEGER PRIMARY KEY,
    product_code TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    description TEXT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS product_color_assets (
    color_asset_id INTEGER PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(product_id) ON DELETE CASCADE,
    color_code TEXT NOT NULL,
    color_name TEXT NOT NULL,
    preview_front_path TEXT NOT NULL,
    preview_back_path TEXT NOT NULL,
    button_96_path TEXT NOT NULL,
    button_300x80_path TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    UNIQUE(product_id, color_code)
);

CREATE INDEX IF NOT EXISTS idx_product_color_assets_product_id ON product_color_assets(product_id);

INSERT OR REPLACE INTO products (product_id, product_code, product_name) VALUES (1, '3001C_BC_UJSST', '3001C Bella + Canvas Unisex Jersey Short-Sleeve T-Shirt');

INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'maroon', 'Maroon', 'assets/img/products/3001C_BC_UJSST/preview/01_maroon_front.png', 'assets/img/products/3001C_BC_UJSST/preview/01_maroon_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/01_maroon_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/01_maroon_300x80.png', 1, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'athletic_heather', 'Athletic Heather', 'assets/img/products/3001C_BC_UJSST/preview/02_athletic_heather_front.png', 'assets/img/products/3001C_BC_UJSST/preview/02_athletic_heather_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/02_athletic_heather_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/02_athletic_heather_300x80.png', 2, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_military_green', 'Heather Military Green', 'assets/img/products/3001C_BC_UJSST/preview/03_heather_military_green_front.png', 'assets/img/products/3001C_BC_UJSST/preview/03_heather_military_green_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/03_heather_military_green_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/03_heather_military_green_300x80.png', 3, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_sand_dune', 'Heather Sand Dune', 'assets/img/products/3001C_BC_UJSST/preview/04_heather_sand_dune_front.png', 'assets/img/products/3001C_BC_UJSST/preview/04_heather_sand_dune_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/04_heather_sand_dune_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/04_heather_sand_dune_300x80.png', 4, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_mauve', 'Heather Mauve', 'assets/img/products/3001C_BC_UJSST/preview/05_heather_mauve_front.png', 'assets/img/products/3001C_BC_UJSST/preview/05_heather_mauve_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/05_heather_mauve_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/05_heather_mauve_300x80.png', 5, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_team_purple', 'Heather Team Purple', 'assets/img/products/3001C_BC_UJSST/preview/06_heather_team_purple_front.png', 'assets/img/products/3001C_BC_UJSST/preview/06_heather_team_purple_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/06_heather_team_purple_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/06_heather_team_purple_300x80.png', 6, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_mint', 'Heather Mint', 'assets/img/products/3001C_BC_UJSST/preview/07_heather_mint_front.png', 'assets/img/products/3001C_BC_UJSST/preview/07_heather_mint_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/07_heather_mint_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/07_heather_mint_300x80.png', 7, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'natural', 'Natural', 'assets/img/products/3001C_BC_UJSST/preview/08_natural_front.png', 'assets/img/products/3001C_BC_UJSST/preview/08_natural_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/08_natural_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/08_natural_300x80.png', 8, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_orange', 'Heather Orange', 'assets/img/products/3001C_BC_UJSST/preview/09_heather_orange_front.png', 'assets/img/products/3001C_BC_UJSST/preview/09_heather_orange_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/09_heather_orange_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/09_heather_orange_300x80.png', 9, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_peach', 'Heather Peach', 'assets/img/products/3001C_BC_UJSST/preview/10_heather_peach_front.png', 'assets/img/products/3001C_BC_UJSST/preview/10_heather_peach_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/10_heather_peach_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/10_heather_peach_300x80.png', 10, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_raspberry', 'Heather Raspberry', 'assets/img/products/3001C_BC_UJSST/preview/11_heather_raspberry_front.png', 'assets/img/products/3001C_BC_UJSST/preview/11_heather_raspberry_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/11_heather_raspberry_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/11_heather_raspberry_300x80.png', 11, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_red', 'Heather Red', 'assets/img/products/3001C_BC_UJSST/preview/12_heather_red_front.png', 'assets/img/products/3001C_BC_UJSST/preview/12_heather_red_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/12_heather_red_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/12_heather_red_300x80.png', 12, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'vintage_black', 'Vintage Black', 'assets/img/products/3001C_BC_UJSST/preview/13_vintage_black_front.png', 'assets/img/products/3001C_BC_UJSST/preview/13_vintage_black_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/13_vintage_black_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/13_vintage_black_300x80.png', 13, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'vintage_white', 'Vintage White', 'assets/img/products/3001C_BC_UJSST/preview/14_vintage_white_front.png', 'assets/img/products/3001C_BC_UJSST/preview/14_vintage_white_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/14_vintage_white_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/14_vintage_white_300x80.png', 14, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'pink', 'Pink', 'assets/img/products/3001C_BC_UJSST/preview/15_pink_front.png', 'assets/img/products/3001C_BC_UJSST/preview/15_pink_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/15_pink_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/15_pink_300x80.png', 15, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'forest', 'Forest', 'assets/img/products/3001C_BC_UJSST/preview/16_forest_front.png', 'assets/img/products/3001C_BC_UJSST/preview/16_forest_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/16_forest_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/16_forest_300x80.png', 16, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'white', 'White', 'assets/img/products/3001C_BC_UJSST/preview/17_white_front.png', 'assets/img/products/3001C_BC_UJSST/preview/17_white_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/17_white_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/17_white_300x80.png', 17, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'yellow', 'Yellow', 'assets/img/products/3001C_BC_UJSST/preview/18_yellow_front.png', 'assets/img/products/3001C_BC_UJSST/preview/18_yellow_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/18_yellow_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/18_yellow_300x80.png', 18, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'asphalt', 'Asphalt', 'assets/img/products/3001C_BC_UJSST/preview/19_asphalt_front.png', 'assets/img/products/3001C_BC_UJSST/preview/19_asphalt_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/19_asphalt_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/19_asphalt_300x80.png', 19, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'deep_teal', 'Deep Teal', 'assets/img/products/3001C_BC_UJSST/preview/20_deep_teal_front.png', 'assets/img/products/3001C_BC_UJSST/preview/20_deep_teal_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/20_deep_teal_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/20_deep_teal_300x80.png', 20, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'heather_royal', 'Heather Royal', 'assets/img/products/3001C_BC_UJSST/preview/21_heather_royal_front.png', 'assets/img/products/3001C_BC_UJSST/preview/21_heather_royal_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/21_heather_royal_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/21_heather_royal_300x80.png', 21, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'kelly', 'Kelly', 'assets/img/products/3001C_BC_UJSST/preview/22_kelly_front.png', 'assets/img/products/3001C_BC_UJSST/preview/22_kelly_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/22_kelly_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/22_kelly_300x80.png', 22, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'red', 'Red', 'assets/img/products/3001C_BC_UJSST/preview/23_red_front.png', 'assets/img/products/3001C_BC_UJSST/preview/23_red_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/23_red_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/23_red_300x80.png', 23, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'leaf', 'Leaf', 'assets/img/products/3001C_BC_UJSST/preview/24_leaf_front.png', 'assets/img/products/3001C_BC_UJSST/preview/24_leaf_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/24_leaf_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/24_leaf_300x80.png', 24, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'team_purple', 'Team Purple', 'assets/img/products/3001C_BC_UJSST/preview/25_team_purple_front.png', 'assets/img/products/3001C_BC_UJSST/preview/25_team_purple_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/25_team_purple_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/25_team_purple_300x80.png', 25, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'true_royal', 'True Royal', 'assets/img/products/3001C_BC_UJSST/preview/26_true_royal_front.png', 'assets/img/products/3001C_BC_UJSST/preview/26_true_royal_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/26_true_royal_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/26_true_royal_300x80.png', 26, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'navy', 'Navy', 'assets/img/products/3001C_BC_UJSST/preview/27_navy_front.png', 'assets/img/products/3001C_BC_UJSST/preview/27_navy_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/27_navy_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/27_navy_300x80.png', 27, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'orange', 'Orange', 'assets/img/products/3001C_BC_UJSST/preview/28_orange_front.png', 'assets/img/products/3001C_BC_UJSST/preview/28_orange_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/28_orange_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/28_orange_300x80.png', 28, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'soft_pink', 'Soft Pink', 'assets/img/products/3001C_BC_UJSST/preview/29_soft_pink_front.png', 'assets/img/products/3001C_BC_UJSST/preview/29_soft_pink_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/29_soft_pink_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/29_soft_pink_300x80.png', 29, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'teal', 'Teal', 'assets/img/products/3001C_BC_UJSST/preview/30_teal_front.png', 'assets/img/products/3001C_BC_UJSST/preview/30_teal_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/30_teal_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/30_teal_300x80.png', 30, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'turquoise', 'Turquoise', 'assets/img/products/3001C_BC_UJSST/preview/31_turquoise_front.png', 'assets/img/products/3001C_BC_UJSST/preview/31_turquoise_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/31_turquoise_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/31_turquoise_300x80.png', 31, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'black', 'Black', 'assets/img/products/3001C_BC_UJSST/preview/32_black_front.png', 'assets/img/products/3001C_BC_UJSST/preview/32_black_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/32_black_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/32_black_300x80.png', 32, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'canvas_red', 'Canvas Red', 'assets/img/products/3001C_BC_UJSST/preview/33_canvas_red_front.png', 'assets/img/products/3001C_BC_UJSST/preview/33_canvas_red_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/33_canvas_red_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/33_canvas_red_300x80.png', 33, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'cardinal', 'Cardinal', 'assets/img/products/3001C_BC_UJSST/preview/34_cardinal_front.png', 'assets/img/products/3001C_BC_UJSST/preview/34_cardinal_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/34_cardinal_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/34_cardinal_300x80.png', 34, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'dark_grey_heather', 'Dark Grey Heather', 'assets/img/products/3001C_BC_UJSST/preview/35_dark_grey_heather_front.png', 'assets/img/products/3001C_BC_UJSST/preview/35_dark_grey_heather_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/35_dark_grey_heather_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/35_dark_grey_heather_300x80.png', 35, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'gold', 'Gold', 'assets/img/products/3001C_BC_UJSST/preview/36_gold_front.png', 'assets/img/products/3001C_BC_UJSST/preview/36_gold_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/36_gold_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/36_gold_300x80.png', 36, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'light_blue', 'Light Blue', 'assets/img/products/3001C_BC_UJSST/preview/37_light_blue_front.png', 'assets/img/products/3001C_BC_UJSST/preview/37_light_blue_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/37_light_blue_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/37_light_blue_300x80.png', 37, 1);
INSERT OR REPLACE INTO product_color_assets (product_id, color_code, color_name, preview_front_path, preview_back_path, button_96_path, button_300x80_path, sort_order, is_active) VALUES (1, 'maize_yellow', 'Maize Yellow', 'assets/img/products/3001C_BC_UJSST/preview/38_maize_yellow_front.png', 'assets/img/products/3001C_BC_UJSST/preview/38_maize_yellow_back.png', 'assets/img/products/3001C_BC_UJSST/buttons/96x96px/38_maize_yellow_96x96.png', 'assets/img/products/3001C_BC_UJSST/buttons/300x80px/38_maize_yellow_300x80.png', 38, 1);
